# Generated by Django 4.0.3 on 2022-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tax_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
